tennis_site/partner/urls.py
from django.urls import path

from . import views

app_name='partner'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('detail/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('result/', views.ResultsView, name='result'),
    path('signup/', views.signup, name='signup'),

    # path('', views.index, name = 'index'),
]

# To be implemented:

    # path('', views.IndexView.as_view(), name='index'),
    # path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),

tennis_site/tennis_site/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('partner/', include('partner.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

tennis_site/partner/models.py
from django.db import models

# Create your models here.

LEVEL_CHOICES = [
    ('1.0', '1.5', '2.0', '2.5', '3.0', '3.5', '4.0', '4.5', '5.0', '5.5', '6.0')
]

class Partner(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    level = models.CharField(max_length=5, choices=LEVEL_CHOICES)
    zipcode = models.IntegerField()
    email = models.EmailField(max_length=254)
    description = models.TextField(default = "I'm a great player")

    class Meta:
        verbose_name = ("partner")
        verbose_name_plural = ("partners")

    def __str__(self):
        return self.last_name

tennis_site/partner/forms.py
from django import forms
from django.forms import ModelForm
from .models import Partner

class PostForm(forms.ModelForm):

    class Meta:
        model = Partner
        fields = ('first_name', 'last_name', 'level', 'zipcode', 'email', 'description')

tennis_site/partner/views.py
from django.http import HttpResponse
from django.shortcuts import redirect,render, get_object_or_404
from django.template import loader
from django.urls import reverse
from django.views import generic

from .forms import PostForm
from .models import Partner

# Create your views here.

# def index(request):
#     return render(request, 'partner/index.html')

# To be implemented:
class IndexView(generic.ListView):
    model = Partner
    template_name = "partner/index.html"

class DetailView(generic.DetailView):
    model = Partner
    template_name = "detail.html"

def ResultsView(request):
    template_name = "results.html"
    query = request.GET.get('q')
    print('what query', query)
    results = Partner.objects.filter(zipcode=query)
    return render(request, template_name, {'results': results})

def signup(request):
    # return HttpResponse("i'm signup")
    template_name= "partner/signup.html"
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            print('post pk is', post.pk)
            post.save()
            return redirect('partner:detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, template_name, {'form': form})

# class ResultsView(generic.DetaiView):
#     model = Partner
#     template_name = "partner/results.html"

tennis_site/partner/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="{% block metadescription %}{% endblock %}">
	<link href="https://fonts.googleapis.com/css2?family=Gloria+Hallelujah&family=Lato&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/703dd68f9d.js" crossorigin="anonymous"></script>
	<title>{% block title %}{% endblock %}</title>
</head>
<body>

	<div class="container">
		{% include 'navbar.html' %}
		{% block content %}{% endblock  %}

    </div>
		{% include 'footer.html' %}


<!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

tennis_site/partner/templates/footer.html
<!-- footer -->
{% comment %} <footer> {% endcomment %}
  <div class="row">
    <div class="col-sm">
    </div>
    <div class="col-sm">
      Jose Nicdao Code Foundry    </div>
    <div class="col-sm">
    </div>
  </div>
{% comment %} </footer> {% endcomment %}

tennis_site/partner/templates/navbar.html
  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="{% url 'partner:index' %}">TennisTinder</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'partner:index' %}">Home<span class="sr-only">(current)</span></a>
        </li>
        {% comment %} <li class="nav-item">
          <a class="nav-link" href="{% url 'partner:detail' %}">My Profile</a>
        </li> {% endcomment %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'partner:signup' %}">Sign Up</a>
        </li>
      </ul>
    </div>
  </nav>

tennis_site/partner/templates/partner/detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="jumbotron">
  <h1 class="display-4">Hello!</h1>
  <p class="lead">Here are the details about your partner {{partner.first_name}}</p>
  <hr class="my-4">
</div>
<div>
  <h2>Details about {{partner.first_name}} </h2>
      <p>  Hello! I'm {{partner.first_name}}
        {{partner.last_name}} and I'm a 
        {{partner.level}} level tennis player. </p>
        I live somewhere near zipcode
        {{partner.zipcode}} so if you're close, you can email me: <!-- email function to be updated -->
        <p><a href="{{ partner.email }}">{{partner.email}}</a>. </p>
        <p>Other things about me: 
        {{partner.description}}</p>
</div>
{% endblock %}

tennis_site/partner/templates/partner/footer.html
<!-- footer -->

<div class="row">
  <div class="col-3"></div>
  <div class="col-6">Jose Nicdao Web Developer Workshop</div>
  <div class="col-3"></div>
</div>

tennis_site/partner/templates/partner/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div class="jumbotron">
    <h1 class="display-4">Welcome to TennisTinder</h1>
    <p class="lead">Find a tennis partner in your area by entering your zipcode below.</p>
    <hr class="my-4">
  </div>

    <div class="row center">
      <div class="col-sm center">
        <form class="form-inline"  action = "result/" method = "GET">
          {% csrf_token %}
          <input class="form-control"   name = 'q' type="text" placeholder="Search" aria-label="Search">
        <button class="btn btn-secondary my-2 my-sm-0"  type="submit">Search</button>
        </form>
      </div>
    </div>
{% endblock %}
  
</body>
</html>

tennis_site/partner/templates/partner/navbar.html
  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="">TennisTinder</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="">Home<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="detail/">My Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="signup/">Sign Up</a>
        </li>
      </ul>
    </div>
  </nav>

tennis_site/partner/templates/partner/results.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="jumbotron">
  <h1 class="display-4">Here are the possible tennis partners in your area</h1>
  <p class="lead">Contact them to schedule a match. Good luck!</p>
</div>

  <table class="table" style="width:100%">
    <thead class="thead-dark">
    <tr>
      <th scope="col">Firstname</th>
      <th scope="col">Lastname</th>
      <th scope="col">Level</th>
      <th scope="col">Zipcode</th>
      <th scope="col">Contact</th>
    </tr>
    </thead>
    <tbody>
      {% for result in results %}            
        <tr>
        <td>{{result.first_name}}</td>
        <td>{{result.last_name}}</td>
        <td>{{result.level}}</td>
        <td>{{result.zipcode}}</td>
        <td><a href="mailto:{{ result.email}}?Subject=Possible Tennis Partner">Contact</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

tennis_site/partner/templates/partner/signup.html
{% extends "base.html" %}
{% load static %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="jumbotron">
        <h1 class="display-4">Join to find tennis partners!</h1>
        <p class="lead">Signup here so we can match you with players in your zipcode area</p>
    </div>
    <div class="row">
        <div class="col-sm">
            <a href="{% url 'partner:signup' %}" class="top-menu"></a>
            <form method="POST" class="post-form">
                {% csrf_token %}
                {{ form | crispy }}
                <button type="submit" class="save btn btn-default">Sign up!</button>
            </form>
        </div>
    </div>
    <br>
    <hr>
{% endblock %}

tennis_site/partner/templates/results.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="jumbotron">
  <h1 class="display-4">Here are the possible tennis partners in your area</h1>
  <p class="lead">Contact them to schedule a match. Good luck!</p>
</div>

  <table class="table" style="width:100%">
    <thead class="thead-dark">
    <tr>
      <th scope="col">Firstname</th>
      <th scope="col">Lastname</th>
      <th scope="col">Level</th>
      <th scope="col">Zipcode</th>
      <th scope="col">Contact</th>
    </tr>
    </thead>
    <tbody>
      {% for result in results %}            
        <tr>
        <td>{{result.first_name}}</td>
        <td>{{result.last_name}}</td>
        <td>{{result.level}}</td>
        <td>{{result.zipcode}}</td>
        <td><a href="mailto:{{ result.email}}?Subject=Possible Tennis Partner">Contact</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% comment %} google map div element {% endcomment %}

<h3>You may enter the zipcode below to access your local map</h3>
{% comment %} something wrong with the map {% endcomment %}
    {% comment %} <div id="map"></div> {% endcomment %}
   <input id="pac-input" class="controls" type="text" placeholder="Search Box">
    <div id="map"></div>

<script async defer
src="https://maps.googleapis.com/maps/api/js?key=&libraries=places&callback=initAutocomplete"></script>

<script src="{% static 'js/script.js' %}"> </script>

{% endblock %}